### PR TITLE
fix(comment): allow new lines in comments on Android

### LINKED ISSUE #206: Cannot add new lines when writing issue comments
Feels weird that pressing return immediately posts the issue comment and there seems to be no way to insert new lines 🤔

### PR DESCRIPTION
**Pull request by lex111**
Fixes #206.

**Need to check on iOS**. There I understand, there was no such problem?

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Nice thank you! Will test this in a bit - will try and solve the issue happening on iOS myself as well 💃

**Comment by lex111** [comment]
@housseindjirdeh what's new? Did you manage to test?

File: src/components/comment-input.component.js [hunk 1]
```diff
@@ -76,8 +77,14 @@ export class CommentInput extends Component {
     };
   }
 
-  handleSubmit = (body: string): void => {
-    this.props.onSubmitEditing(body);
+  handleSubmitEditing = (body: string): void => {
+    if (Platform.OS === 'android') {
```
Comment (lex111) [inline src/components/comment-input.component.js]: @housseindjirdeh If there is this problem on iOS, can this condition be removed? It is necessary to check on iOS with these changes, and then you can remove this condition, and check without it.

**Comment by housseindjirdeh** [comment]
My apologies, my week has been swamped and I haven't had the chance to test it :( If not today then hopefully tomorrow and I'll let you know. The thing with iOS is that it's just the return key that's causing to post and I feel like there should be a prop or something similar to do newline instead. 🤔

**Comment by lex111** [comment]
@housseindjirdeh so by pressing the return key, a new line should be inserted? I thought the matter in the `onSubmitEditing` handler, because it was sending a message, and now it happens in the `onSubmit` handler. Perhaps this will help for iOS?

File: src/issue/screens/issue.screen.js [hunk 2]
```diff
@@ -301,7 +301,7 @@ class Issue extends Component {
               }
               issueLocked={issue.locked}
               language={language}
-              onSubmitEditing={this.postComment}
```
Comment (lex111) [inline src/issue/screens/issue.screen.js]: Now you can only set the `onSubmit` handler.

File: src/components/comment-input.component.js [hunk 3]
```diff
@@ -113,12 +120,12 @@ export class CommentInput extends Component {
                   : translate('issue.main.commentInput', language)
               }
               multiline
-              blurOnSubmit
+              blurOnSubmit={false}
               onChangeText={text => this.setState({ text })}
               onContentSizeChange={event =>
                 this.setState({ height: event.nativeEvent.contentSize.height })}
               onSubmitEditing={event =>
```
Comment (Antoine38660) [inline src/components/comment-input.component.js]: According to the [doc](https://facebook.github.io/react-native/releases/0.47/docs/textinput.html#onsubmitediting) the `onSubmitEditing` is useless

Comment (lex111) [inline src/components/comment-input.component.js]: Yes, but even if it is removed (or `false`), the problem remains. As I wrote, this is due to non-standard keyboards (on Android at least). Therefore, need to add an new line. I do not know how things are on iOS? Maybe there is enough to remove `blurOnSubmit`.

Comment (Antoine38660) [inline src/components/comment-input.component.js]: I just tried to post a comment with new line from the iOS simulator and nothing was posted... simulator screen shot 12 aout 2017 a 21 28 22

Comment (lex111) [inline src/components/comment-input.component.js]: Rather, it's because of my other changes, I changed the handlers? It would be cool to solve this on iOS, because everything is good on Android.

Comment (Antoine38660) [inline src/components/comment-input.component.js]: Ok, so let me try to fix this one for iOS :)

Comment (lex111) [inline src/components/comment-input.component.js]: It will break afterwards, when this PR merge?

File: src/components/comment-input.component.js (hunk 1 above)
Comment (Antoine38660) [inline src/components/comment-input.component.js]: You can remove the condition, np with iOS

File: src/components/comment-input.component.js (hunk 3 above)
Comment (Antoine38660) [inline src/components/comment-input.component.js]: After some tests, in the logger, I have `{type: "POST_ISSUE_COMMENT_SUCCESS", payload: {message: "Not Found", documentation_url: "https://developer.github.com/v3"}}`.

File: src/components/comment-input.component.js (hunk 1 above)
Comment (lex111) [inline src/components/comment-input.component.js]: Then new lines will be added to iOS, did you check?

Comment (Antoine38660) [inline src/components/comment-input.component.js]: Yes it tested without the condition, new lines are added but it still "a bug" when I post the comment (nothing is posted)

File: src/components/comment-input.component.js (hunk 3 above)
Comment (lex111) [inline src/components/comment-input.component.js]: It seems I figured out what I did wrong: TexInput does not have the `onSubmit` handler, and I just changed `onSubmitEditing` to `onSubmit`, but it's strange, then it should not work at all, in the sense that the sending should not happen at all, but Android works.

I'll check it again later.

Comment (Antoine38660) [inline src/components/comment-input.component.js]: But the `onSubmitEditing` handler is no more required if we have `blurOnSubmit={false}`

Comment (lex111) [inline src/components/comment-input.component.js]: What kind of handler is needed to send?

Comment (Antoine38660) [inline src/components/comment-input.component.js]: Idk, can you post a comment from Android (with these changes)?

Comment (lex111) [inline src/components/comment-input.component.js]: Yes, it's sent ... and wait .. After all, we have a comment sent only by [the "Post" button](https://github.com/lex111/git-point/blob/d1668b4e0cd1e003554991efaa0109cd30caa0c4/src/components/comment-input.component.js#L146), just there is a send handler.

Comment (Antoine38660) [inline src/components/comment-input.component.js]: I think it's sufficient :)

Comment (lex111) [inline src/components/comment-input.component.js]: I do not understand why iOS does not work? Do I need to remove the condition?

**Comment by Antoine38660** [comment]
This is a test sent from iOS

With new lines.

**Comment by lex111** [comment]
@Antoine38660 It is perfectly! It turns out we can merge?
