### PR TITLE
fix(md): Image related fixes

### LINKED ISSUE #437: Descriptions of some issues are missing
For example, #433, #434.

@machour I am afraid that it is related with markdown rendering. I got the familiar error when visiting these 2 issues in simulator.

### PR DESCRIPTION
**Pull request by machour**
This fix should be a bit more solid:

- enhance `` extraction from spans
- if it didn't work, and an `` is in a `<span>` at render time, render it as a label
- check `<ul>`|`<ol>` for lists, instead of `<li>` cause I need to remove the `<li>` for tasks, which breaks the detecetion

Should fix  #437, #363 and #429

### CODE REVIEW

File: src/components/github-htmlview.component.js [hunk 1]
```diff
@@ -344,7 +348,7 @@ export class GithubHtmlView extends Component {
           _index,
           _siblings,
           _parent,
-          _defaultRenderer,
+          _defaultRenderer
```
Comment (chinesedfan) [inline src/components/github-htmlview.component.js]: @machour It seems your IDE configurations are not consistent with our ESLint rules. We require tail commas as I know.

Comment (andrewda) [reply src/components/github-htmlview.component.js]: Interesting. Prettier should run on commit and fix all these, though.

Comment (housseindjirdeh) [reply src/components/github-htmlview.component.js]: Yeah our prettier pre-commit hook should be taking care of this :thinking:

Comment (machour) [reply src/components/github-htmlview.component.js]: Sorry for that guys, I tried to enhance my VSCode settings yesterday, this is related.

But something I don't quiet understand about prettier, is that it always seems to modify the files **after** my commit. 

Is it because I don't use `git add` in my workflow, but instead I do a `git commit` passing paths to the files I changed?

Comment (chinesedfan) [reply src/components/github-htmlview.component.js]: We have [precommit script](https://github.com/gitpoint/git-point/blob/master/package.json#L21), whose details are [here](https://github.com/gitpoint/git-point/blob/master/package.json#L41). Once you want to commit something, prettier will modify your codes <strong>first</strong>, then finish the commit process.

It does't matter whether you use `git add` or not. There will be always a `git add` in the precommit script.

Comment (lex111) [reply src/components/github-htmlview.component.js]: At me by the way have ceased to work git hooks, what it is necessary to make, that they again earned?

**Comment by machour** [comment]
@chinesedfan, this is not what I've been observing on my end. For me, I'm
seeing this:

git commit -m "my changes" file.js
git push
git status

I'll see file.js modified and staged for commit.

So I have to do a second push?

On Oct 8, 2017 13:21, "Alexey Pyltsyn" <notifications@github.com> wrote:

*@lex111* commented on this pull request.
------------------------------

In src/components/github-htmlview.component.js
<https://github.com/gitpoint/git-point/pull/448#discussion_r143353266>:

> @@ -344,7 +348,7 @@ export class GithubHtmlView extends Component {
           _index,
           _siblings,
           _parent,
-          _defaultRenderer,
+          _defaultRenderer

At me by the way have ceased to work git hooks, what it is necessary to
make, that they again earned?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitpoint/git-point/pull/448#discussion_r143353266>, or mute
the thread
