### PR TITLE
fix(profile): navigate to AuthProfile for current user

### LINKED ISSUE #247: Navigate to AuthProfileScreen for the Current User
**Current process**

- I could find my own profile via Search menu navigation (for Users) and try to follow myself via triple dots menu "..." (at top right corner of the screen).
screen shot 2017-08-13 at 8 53 46 pm

**Suggestion**

- How about we remove that menu if the profile that we searched for is our own profile?

What do you guys think? @housseindjirdeh @andrewda

### PR DESCRIPTION
**Pull request by wlisrausr**
Closes #247 

- [x] Make `UserListItem` component stateful
- [x] Map the component to `state.auth.user` 
- [x] Navigate the current user to `AuthProfileScreen`

### CODE REVIEW

File: src/components/user-list-item.component.js [hunk 1]
```diff
@@ -72,81 +61,108 @@ const styles = StyleSheet.create({
...
-        <UserComponent
-          style={styles.userInfo}
-          onPress={() =>
-            navigation.navigate('Profile', {
-              user,
-            })}
-        >
-          <ImageContainerComponent
-            style={styles.avatarContainer}
+    const CorrectScreen =
```
Comment (lex111) [inline src/components/user-list-item.component.js]: Variable names are written in lowerCamelCase.

File: src/components/user-list-item.component.js [hunk 2]
```diff
@@ -72,81 +61,108 @@ const styles = StyleSheet.create({
...
+          )}
+        underlayColor={colors.greyLight}
+        style={!noBorderBottom && styles.borderContainer}
+      >
+        <View style={styles.wrapper}>
+          <UserComponent
+            style={styles.userInfo}
             onPress={() =>
-              navigation.navigate('Profile', {
+              navigation.navigate(CorrectScreen ? 'AuthProfile' : 'Profile', {
```
Comment (lex111) [inline src/components/user-list-item.component.js]: You can just left `CorrectScreen`, because we store the name of the screen, then you do not need a ternary operator.

File: src/components/user-list-item.component.js [hunk 3]
```diff
@@ -72,81 +61,108 @@ const styles = StyleSheet.create({
...
-              style={styles.avatar}
-              source={{
-                uri: user.avatar_url,
-              }}
-            />
-          </ImageContainerComponent>
+            <ImageContainerComponent
+              style={styles.avatarContainer}
+              onPress={() =>
+                navigation.navigate(CorrectScreen ? 'AuthProfile' : 'Profile', {
```
Comment (lex111) [inline src/components/user-list-item.component.js]: Similarly, see above.

File: src/components/user-list-item.component.js (hunk 1 above)
Comment (wlisrausr) [inline src/components/user-list-item.component.js]: Ah, my bad. I'll fix it

File: src/components/user-list-item.component.js (hunk 2 above)
Comment (wlisrausr) [inline src/components/user-list-item.component.js]: Got it
