### PR TITLE
fix(share): stop pre-filling email subject

### LINKED ISSUE #228: Don't pre-fill the email subject
Currently, if I click on the email action in a user profile, my email application opens with a pre-filled subject "Hi !".

I don't think this is a good behavior:
- I might forget to edit the subject, and my mailer won't warn me
- "Hi !" is really not a good email subject, and we shouldn't encourage users to use it

I know, I'm picky 🤓

### PR DESCRIPTION
**Pull request by machour**
Tested on Android only as I didn't succeed in running it on iOS (See #29)

### CODE REVIEW

File: src/components/entity-info.component.js [hunk 1]
```diff
@@ -124,7 +124,7 @@ export const EntityInfo = ({ entity, orgs, language, navigation }: Props) => {
           subtitle={entity.email}
           subtitleStyle={styles.listSubTitle}
           onPress={() =>
-            Communications.email([entity.email], null, null, 'Hi!', '')}
+            Communications.email([entity.email], null, null, null, '')}
```
Comment (andrewda) [inline src/components/entity-info.component.js]: While not technically under the scope of this PR, could you change the last value to `null`, too, instead of an empty string? They both work, but the react-native-communications documentation says `null` is the way to go.

Comment (machour) [inline src/components/entity-info.component.js]: There you go: https://github.com/gitpoint/git-point/pull/229/commits/14d719fee6894eb98d3a2ec45e40cd046e1a477a
Thanks for the quick review :)

**Comment by lex111** [comment]
@machour just wondering how this fix solves #29?

**Comment by lex111** [comment]
@machour strange, it seems that not work git hooks for you?

**Comment by machour** [comment]
@lex111 indeed, it does not: 

```
git commit -m "Pass null for body as well" src/components/entity-info.component.js
husky > npm run -s precommit (node v8.1.3)

 ✔ Running tasks for *.js
husky > npm run -s commitmsg (node v8.1.3)

⧗   input: Pass null for body as well
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
```

Provided that the change is simple and tested on an actual device, I allowed myself a `--no-verify`
I'm on gitter if you want to investigate this

**Comment by andrewda** [comment]
@machour The hook that's failing there is for the commit message. It should be something like `fix(share): stop pre-filling email subject`

**Comment by machour** [comment]
Duly noted for next commit messages. Thanks a lot !

**Comment by housseindjirdeh** [comment]
Thanks a million for this @machour <3

Don't forget to add yourself as a contributor with [`yarn constributors:add`](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#setup)!!!!
